name: CI

on: [pull_request]

jobs:
  stylecheck:
    runs-on: ubuntu-20.04
    steps:
      # Check out the repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v2
      - uses: DoozyX/clang-format-lint-action@v0.13
        with:
          source: './src'
          clangFormatVersion: 12

  buildcheck:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        compiler: [g++-10, clang++-12]

    steps:
      # Check out the repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v2
      # Install any necessary programs
      - name: Configure Environment
        run: sudo apt-get install ninja-build clang-tidy-12 libboost-all-dev
      # Note: the "build all" action isn't strictly necessary because "make test"
      #       will also do the builds, but doing this as two steps will make the
      #       output easier to read.
      - name: Build All
        env:
          CXX: ${{ matrix.compiler }}
        run: CMAKE_BUILD_TYPE="Release" CMAKE_CXX_FLAGS="-Werror" CMAKE_EXTRA_FLAGS="-DUSE_CLANG_TIDY=ON -DCLANG_TIDY_ERRORS=ON" make all
      - name: Test All
        run: make test
      - name: Run Benchmarks
        run: make bench
