name: Performance Tracking

on:
  push:
    branches:
      - master

jobs:
  benchmark:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        compiler: [g++-11, clang++-12]

    steps:
      # Check out the repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v2
      # Install any necessary programs
      - name: Configure Environment
        run: sudo apt-get install ninja-build clang-tidy-12 libboost-all-dev
      - name: Run Benchmarks
        run: make bench
      - name: Store Benchmark Results
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: C++ Benchmark
          tool: 'googlecpp'
          output-file-path: build/benchmark_results.json
          alert-threshold: '50%'
          fail-on-alert: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-comment-cc-users: '@gregbartell'
